export const PREFIXE_TCHAT : string = "tchat";
export const PREFIXE_DISTRIBUTION: string = "distribution";
export const CODE : string = "code"
export const SUFFIXE_ETOILE : string = "etoile";
export const SUFFIXE_JEU1 : string = "jeu1";
export const SUFFIXE_ANNEAU : string = "anneau";
export const ENVOI : string = "envoi";
export const RECEPTION : string = "reception";
export const PREFIXE_ACCUEIL: string = "accueil";
export const PREFIXE_AUTH: string = "auth";